apiVersion: apps/v1
kind: Deployment
metadata:
  name: jimmy-app
  labels:
    app: jimmy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jimmy-app
  template:
    metadata:
      labels:
        app: jimmy-app
    spec:
      containers:
        - name: jimmy-app
          image: asia-east1-docker.pkg.dev/smiling-stock-425106-c9/devops-repo/jimmy-app:2
          ports:
            - containerPort: 80
