apiVersion: v1
kind: Service
metadata:
  name: jimmy-app-service
  labels:
    app: jimmy-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: jimmy-app
